language: node_js
node_js: '10'
services: mongodb
env:
  matrix:
  - MONGODB_URI=mongodb://localhost:27017/test
deploy:
  provider: heroku
  app:
    master: nanny-now-production
    dev: nanny-now-staging
  api_key:
    secure: Thg/ZBhF2wC+d12t7xlQKuLiWOAe7Bwo8PHDdTNYRqCTI97opUiNGEhyR9RESVTt9dEUYPT8tipWeCkAtpWKTZi7X9bZBhof/JlMdUhnFrYxsNCjJ3XHgTBNeYhyYXOMYzLQe5H0QDoYliKdsWNQ07l5FyDoECodUZ6pKnoauROzMwSWLLRqQYtY/L+5HkV8HiKY3q/Oe9mQ35EOeKqpSGU9BQ1MuLRbKP2mAt5+e+j2VnHRwR3TUbt1cT2VdsK+28/+w62hhOkPaycC4qP4NIW7GlKlklKYoN/C5aeElENO/NIXyyjYuKGUwYXptOWELTXmKNTfIc/q/bRIlFc6IXqMXvi69aBSbYEaDvCfndfCj0M9rWTRn6H4TV+fkkt5w3qRrUO9s4aivjTteFYToNgFy61oUlLvJArjHsEp3XVsEtIodxrnFYKnaiK5/wY33FwP5fwXuKia77wZwJ6KUqtFrGCedWTV58OHzvmA0Zc7Ub2D3kyHh3TyF5oGvNUEDLofzkZgOJ121XuncP1gT+6vm5vErdgJkJckOfePHpJ6u+1sOaAPXikqY8RndeF3UxgJqcx3zpVh+688f6jGddmlEnHX+RuLKymSLbTcJDKeNX3d2pRZOnOY3YROKm3apBgKZMwMD13mKM3qC0ZGV//eR5CXOurLebfijHdaHWI=
